<div style="text-align:justify">
    <h2><?= e($title) ?></h2>
    <p>This website processes - in accordance with article 6 first subparagraph point (f) of the <a href="https://commission.europa.eu/law/law-topic/data-protection/data-protection-eu_en">European General Data Protection Regulation</a> - personal data for genealogical research purposes as reflected in this privacy statement. I hereby distinguish between personal data that I process for the purpose of my genealogical research and personal data that you provide to me yourself when you create a free user account on this website.

    <ol>
        <h4><li>Personal data for the purpose of genealogical research</li></h4>
        <p>I process personal data from public sources (archives, newspapers, websites, etc), from my own sources or because you or someone else has provided it to me for the purpose of my genealogical research . Visitors have limited access to data on deceased persons: those who died more than 10 years ago or those born more than 120 years ago. Members with a user account also have access to:</p>

        <ul>
            <li>data of deceased persons</li>
            <li>(limited) data of living persons to whom they are related in the first or second degree (partner, (step)child, grandchild, parent, grandparent, uncle/aunt)</li>
            <li>own data</li>
        </ul><br />

        <p>Special personal data (see below) are always protected, even for registered close relatives. You can always request to see your own data collected for my genealogical research, even if you do not have a user account. If you do not want your data to be viewable by registered close relatives, please let me know via the <a href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">contact form</a>.</p>

        <h5>Special and/or sensitive personal data</h5>
        <p>For my genealogical research, I process special and/or sensitive personal data from public sources (archives, newspapers, websites, etc), from my own sources or because you or someone else has provided it to me. Below is a list of the special personal data I may process for the purpose of my genealogical research:</p>

        <ul>
            <li>racial or ethnic origin</li>
            <li>political opinions</li>
            <li>religion or belief</li>
            <li>union membership</li>
            <li>health</li>
            <li>criminal record</li>
        </ul><br />

        <p>I do not release this data until 10 years after your death. This also applies to data obtained from public sources.</p>

        <h5>How long your personal data is kept</h5>
        <p>Your personal data will not be kept longer than strictly necessary to fulfil the purposes for which your data is collected. If you have not been active on our website for 3 years, your membership will be terminated and the personal data associated with your account will be deleted. The personal data processed on your personal page for the purpose of my genealogical research are never deleted. I consider these data to be of historical importance for my genealogical research. However, you can demand from me that these data may only be viewed by the researcher himself and not by registered close relatives. Your personal page is therefore completely protected for members of this website. Your data are always protected from visitors to this website..</p>

        <h5>Sharing personal data with third parties</h5>
        <p>Data on this website may only be used for personal purposes. <strong>Any other use of this data is expressly prohibited.</strong> I never provide your account data to third parties. Making family tree data available to third parties (other genealogists) is limited to persons who died more than 10 years ago. I never share data I have collected about you and other living family members for the purpose of genealogical research, unless you give your explicit permission..</p>

        <h4><li>Personal data on behalf of a user account on this website</li></h4>
        <p>This website processes your personal data when you provide it to me yourself when creating an account. Below is an overview of the personal data I process when you create a user account:</p>

        <ul>
            <li>Name</li>
            <li>E-mail address</li>
            <li>IP address</li>
            <li>Other personal data that you actively provide e.g. by completing your personal data on your person page or by making family links. This also includes additional information you provide to me via email or otherwise.</li>
            <li>Data about your activities on this website</li>
        </ul><br />

        <p>I occasionally use your email address to email you about important matters relating to the website or to contact you if necessary. When you delete your user account, the genealogical data on your person page will be retained for the purpose of my genealogical research.</p>

        <h5>View, correct or delete data</h5>
        <p>You have the right to view, correct or delete your personal data belonging to your user account. You can do this yourself via the personal settings of your account. You also have the right to withdraw your possible consent to data processing or object to the processing of your personal data. You have the right to inspect and correct the data I have collected about you for the purpose of my genealogical research. You can also request that I never disclose this data to third parties as long as you are alive.</p>

        <p>If you wish to exercise your right to object or have other questions/comments about data processing, please use the <a href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">contact form</a> to send me an itemised request.</p>

        <h4><li>How are your personal data protected?</li></h4>
        <p>I take the protection of your data seriously and take appropriate measures to prevent misuse, loss, unauthorised access, unwanted disclosure and unauthorised modification. If you have the impression that your data is not properly secured or there are indications of misuse, please contact me via the <a href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">contact form</a>.</p>

        <h4><li>Cookies or similar techniques, used on this website</li></h4>
        <p>This website only uses technical and functional cookies. We also use analytical cookies that do not infringe on your privacy. A cookie is a small text file that is stored on your computer, tablet or smartphone the first time you visit this website. The cookies used by this website are necessary for the technical operation of the website and your ease of use. They ensure that the website works properly and, for example, remember your preferred settings such as the language you selected. They also allow me to optimise my website. You can opt out of cookies by setting your internet browser to stop storing cookies. In addition, you can also delete any information previously stored via your browser settings.</p>


    </ol>
</div>