<div style="text-align:justify">
    <h2><?= e($title) ?></h2>
    <p>Deze website verwerkt - in overeenstemming met artikel 6, eerste lid, onderdeel f) van de <a href="https://commission.europa.eu/law/law-topic/data-protection/data-protection-eu_nl">Europese Algemene Verordening Gegevensbescherming</a> -  persoonsgegevens voor genealogisch onderzoek zoals weergegeven in deze privacyverklaring. Ik maak hierbij onderscheid tussen persoonsgegevens die ik verwerk ten behoeve van mijn genealogisch onderzoek en persoonsgegevens die u zelf aan mij verstrekt wanneer u een gratis gebruikersaccount op deze website aanmaakt.</p>

    <ol>
        <h4><li>Persoonsgegevens ten behoeve van genealogisch onderzoek</li></h4>
        <p>Ik verwerk persoonsgegevens uit openbare bronnen (archieven, kranten, websites, etc), uit eigen bron of doordat u of iemand anders deze ten behoeve van mijn genealogisch onderzoek aan mij heeft verstrekt . Bezoekers hebben een beperkte toegang tot gegevens van overledenen: personen die meer dan 10 jaar geleden zijn overleden of personen die meer dan 120 jaar geleden zijn geboren. Leden met een gebruikersaccount hebben daarnaast ook toegang tot:</p>

        <ul>
            <li>gegevens van overledenen</li>
            <li>(beperkte) gegevens van levende personen aan wie zij in de eerste of tweede graad (partner, (stief)kind, kleinkind, ouder, grootouder, oom/tante) verwant zijn</li>
            <li>eigen gegevens</li>
        </ul><br />

        <p>Bijzondere persoonsgegevens (zie hieronder) worden altijd afgeschermd, ook voor geregistreerde naaste familieleden. U kunt altijd een verzoek indienen om uw eigen gegevens te mogen inzien die ik voor mijn genealogisch onderzoek hebben verzameld, ook als u geen gebruikersaccount heeft. Indien u niet wilt dat uw gegevens kunnen worden ingezien door geregistreerde naaste familieleden, dan kunt u mij dit laten weten via het <a href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">contactformulier</a>.</p>

        <h5>Bijzondere en/of gevoelige persoonsgegevens</h5>
        <p>Voor mijn genealogisch onderzoek verwerk ik bijzondere en/of gevoelige persoonsgegevens uit openbare bronnen (archieven, kranten, websites, etc), uit eigen bron of doordat u of iemand anders deze aan mij heeft verstrekt. Hieronder vindt u een overzicht van de bijzondere persoonsgegevens die ik mogelijk ten behoeve van mijn genealogisch onderzoek verwerk:</p>

        <ul>
            <li>ras of etnische afkomst</li>
            <li>politieke opvattingen</li>
            <li>godsdienst of levensovertuiging</li>
            <li>lidmaatschap van een vakbond</li>
            <li>gezondheid</li>
            <li>strafrechtelijk verleden</li>
        </ul><br />

        <p>Ik geef deze gegevens niet eerder dan 10 jaar na uw overlijden vrij. Dit is ook van toepassing op gegevens die afkomstig zijn uit openbare bronnen.</p>

        <h5>Hoe lang u persoonsgegevens worden bewaard</h5>
        <p>Uw persoonsgegevens worden niet langer bewaard dan strikt noodzakelijk is om de doelen te realiseren waarvoor uw gegevens worden verzameld. Indien u 3 jaar niet actief bent geweest op onze website, wordt uw lidmaatschap beëindigd en worden de persoonsgegevens die verbonden zijn aan uw account verwijderd. De persoonsgegevens die op uw persoonspagina ten behoeve van mijn genealogisch onderzoek verwerkt zijn worden nooit verwijderd. Ik acht deze gegevens van historisch belang voor mijn genealogisch onderzoek. U kunt wel van mij eisen dat deze gegevens alleen ingezien mogen worden door de onderzoeker zelf en niet door geregistreerde naaste familieleden. Uw persoonspagina wordt dan ook volledig afgeschermd voor leden van deze website. Uw gegevens zijn altijd afgeschermd voor bezoekers van deze website.</p>

        <h5>Delen van persoonsgegevens met derden</h5>
        <p>Gegevens op deze website mogen alleen worden gebruikt voor persoonlijke doeleinden. <strong>Ander gebruik van deze gegevens is uitdrukkelijk niet toegestaan.</strong> Ik verstrek uw accountgegevens nooit aan derden. Het ter beschikking stellen van stamboomgegevens aan derden (andere genealogen) is beperkt tot personen die meer dan 10 jaar geleden zijn overleden. Gegevens die ik ten behoeve van miin genealogisch onderzoek over u en andere nog levende familieleden verzameld heb deel ik nooit met derden, tenzij u daar zelf uitdrukkelijk toestemming voor geeft.</p>

        <h4><li>Persoonsgegevens ten behoeve van een gebruikersaccount op deze website</li></h4>
        <p>Deze website verwerkt uw persoonsgegevens wanneer u deze zelf aan mij verstrekt bij het aanmaken van een account. Hieronder vindt u een overzicht van de persoonsgegevens die ik verwerk wanneer u een gebruikersaccount aanmaakt:</p>

        <ul>
            <li>Naam</li>
            <li>E-mailadres</li>
            <li>IP-adres</li>
            <li>Overige persoonsgegevens die u actief verstrekt bijvoorbeeld door uw persoonsgegevens op uw persoonspagina aan te vullen of door het leggen van familiebanden. Hieronder valt ook extra informatie die u mij via e-mail of op andere wijze verstrekt.</li>
            <li>Gegevens over uw activiteiten op deze website</li>
        </ul><br />

        <p>Ik gebruik uw e-mailadres incidenteel om u te mailen over belangrijke zaken met betrekking tot de website of om contact met u op te nemen indien dat noodzakelijk is. Wanneer u uw gebruikersaccount verwijderd blijven de genealogische gegevens op uw persoonspagina behouden ten behoeve van mijn genealogisch onderzoek.</p>

        <h5>Gegevens inzien, aanpassen of verwijderen</h5>
        <p>U heeft het recht om uw persoonsgegevens behorende bij uw gebruikersaccount in te zien, te corrigeren of te verwijderen. Dit kunt u zelf doen via de persoonlijke instellingen van uw account. Daarnaast heeft u het recht om uw eventuele toestemming voor de gegevensverwerking in te trekken of bezwaar te maken tegen de verwerking van uw persoonsgegevens. U heeft het recht om de gegevens die ik ten behoeve van mijn genealogisch onderzoek over u heb verzameld in te zien en te corrigeren. Ook kunt u van mij verlangen dat deze gegevens nooit aan derden wordt verstrekt zolang u in leven bent.</p>

        <p>Wilt u gebruik maken van uw recht op bezwaar of heeft u andere vragen/opmerkingen over de gegevensverwerking, gebruik dan het <a href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">contactformulier</a> om mij een gespecificeerd verzoek te sturen.</p>

        <h4><li>Hoe worden uw persoonsgegevens beveiligd?</li></h4>
        <p>Ik neem de bescherming van uw gegevens serieus en neem passende maatregelen om misbruik, verlies, onbevoegde toegang, ongewenste openbaarmaking en ongeoorloofde wijziging tegen te gaan. Als u de indruk heeft dat uw gegevens niet goed beveiligd zijn of er aanwijzingen zijn van misbruik, neem dan contact op via het <a href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">contactformulier</a>.</p>

        <h4><li>Cookies, of vergelijkbare technieken, die op deze website gebruikt worden</li></h4>
        <p>Deze website gebruikt alleen technische en functionele cookies. Daarnaast ook analytische cookies die geen inbreuk maken op uw privacy. Een cookie is een klein tekstbestand dat bij het eerste bezoek aan deze website wordt opgeslagen op uw computer, tablet of smartphone. De cookies die deze website gebruikt zijn noodzakelijk voor de technische werking van de website en uw gebruiksgemak. Ze zorgen ervoor dat de website naar behoren werkt en onthouden bijvoorbeeld uw voorkeursinstellingen zoals de taal die u heeft geselecteerd. Ook kan ik hiermee mijn website optimaliseren. U kunt zich afmelden voor cookies door uw internetbrowser zo in te stellen dat deze geen cookies meer opslaat. Daarnaast kunt u ook alle informatie die eerder is opgeslagen via de instellingen van uw browser verwijderen.</p>


    </ol>
</div>