<div style="text-align:justify">
    <h2><?= e($title) ?></h2>

    <h5>Introduction</h5>
    <p>This website processes personal data for genealogical research purposes in accordance with article 6 first subparagraph point (f) of the <a class="text-primary" href="https://commission.europa.eu/law/law-topic/data-protection/data-protection-eu_en">General Data Protection Regulation</a> (GDPR) as set out in this privacy statement. I distinguish between personal data that I process for the purpose of my genealogical research and personal data that you provide to me yourself when you create a free user account on this website.</p>

    <ol>
        <h4><li>Personal data for the purpose of genealogical research</li></h4>
        <p>I process personal data from public sources (archives, newspapers, websites, etc.), from my own sources or because you or someone else has provided it to me for the purpose of my genealogical research. Visitors have limited access to the data of deceased persons: People who died more than 10 years ago, or people born more than 120 years ago. Members with a user account also have access to:</p>

        <ul>
            <li>data of deceased persons</li>
            <li>(limited) data of living persons to whom they are related in the first or second degree (partner, (step)child, grandchild, parent, grandparent, uncle/aunt)</li>
            <li>own data</li>
        </ul><br />

        <p>Specific personal data (see below) are always protected, even for registered close relatives. You can always request to see your own data collected for my genealogical research, even if you do not have a user account. If you do not want your data to be viewable by registered close relatives, please let me know via the <a class="text-primary" href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">contact form</a>.</p>

        <h5>Specific and/or sensitive personal data</h5>
        <p>For my genealogical research, I process specific and/or sensitive personal data from public sources (archives, newspapers, websites, etc), from my own sources or because you or someone else has provided it to me. Below is a list of the specific personal data I may process for the purpose of my genealogical research:</p>

        <ul>
            <li>racial or ethnic origin</li>
            <li>political opinions</li>
            <li>religion or belief</li>
            <li>union membership</li>
            <li>health</li>
            <li>criminal record</li>
        </ul><br />

        <p>I do not release this data until 10 years after your death. This also applies to data obtained from public sources.</p>

        <h5>Storage period of your personal data</h5>
        <p>Your personal data will not be retained for longer than is strictly necessary to fulfil the purposes for which it was collected. If you have not been active on our website for 3 years, your membership will be terminated and the personal data associated with your account will be deleted. The personal data processed on your personal page for the purpose of my genealogical research will never be deleted. I believe that this data is of historical importance for my genealogical research.</p>

        <p>However, you may request from me that this data may only be viewed by the researcher himself and not by registered close relatives. Your personal page is therefore fully protected for members of this website. Your data is also protected from visitors to this website at all times.</p>

        <h5>Disclosure of personal data to third parties</h5>
        <p>The data on this website may only be used for personal purposes.</p>

        <p><strong>Any other use of this data is expressly prohibited.</strong></p>

        <p>I will never pass on your account details to third parties. The provision of family tree data to third parties (other genealogists) is limited to persons who died more than 10 years ago. I never share the data I have collected about you and other living family members for the purpose of genealogical research unless you give your express consent.</p>

        <h4><li>Personal data for the purpose of a user account on this website</li></h4>
        <p>This website processes your personal data on the basis of art. 6 (1) lit. f DSGVO if you provide it to me yourself when creating an account. Below is an overview of the personal data I process when you create a user account:</p>

        <ul>
            <li>Name</li>
            <li>E-mail address</li>
            <li>IP address</li>
            <li>Other personal data that you actively provide e.g. by completing your personal data on your person page or by making family links. This also includes additional information you provide to me via email or otherwise.</li>
            <li>Data about your activities on this website</li>
        </ul><br />

         <h5>Use of your data</h5>
        <p>I may occasionally use your email address to contact you by email about important matters relating to the website or to contact you if necessary. If you delete your account, the genealogical data on your person page will remain for the purpose of my genealogical research.</p>

        <h5>View, correct or delete data</h5>
        <p>You have the right to view, correct or delete your personal data belonging to your user account. You can do this yourself via the personal settings of your account. You also have the right to withdraw your possible consent to data processing or object to the processing of your personal data. You have the right to inspect and correct the data I have collected about you for the purpose of my genealogical research. You can also request that I never disclose this data to third parties as long as you are alive.</p>

        <p>If you wish to exercise your right to object or have other questions/comments about data processing, please use the <a class="text-primary" href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">contact form</a> to send me an itemised request.</p>

        <h4><li>Right of appeal to the competent supervisory authority</li></h4>
        <p>In the event of breaches of the GDPR, data subjects shall have a right of appeal to a supervisory authority, in particular in the Member State of their habitual residence, their place of work or the place of the alleged breach. The right of appeal is without prejudice to other administrative or judicial remedies.</p>

        <h4><li>Hosting</h4></li>
        <p>This website is hosted by an external service provider (hoster). The personal data collected on this website is stored on the hoster's servers. This may include IP addresses, contact requests, meta and communication data, contract data, contact details, names, website accesses and other data generated via a website. My hoster will only process your data to the extent necessary to fulfil its performance obligations and will follow my instructions in relation to such data.</p>

        <p>The hoster is used in the interest of a secure, fast and efficient provision of my online offer by a professional provider (art. 6 (1) lit. f DGPR). I use the following hoster for this purpose:<p/>

        <p>STRATO AG<br />
        Pascalstraße 10<br />
        10587 Berlin</p>

        <h5>Conclusion of an order processing contract</h5>
        <p>In order to ensure data protection-compliant processing, I have concluded an order processing contract with my hoster..</p>

        <h4><li>How is your personal data protected?</li></h4>
        <p>I take the protection of your data seriously and take appropriate measures to prevent misuse, loss, unauthorised access, unwanted disclosure and unauthorised modification. If you have the impression that your data is not properly secured or there are indications of misuse, please contact me via the <a class="text-primary" href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">contact form</a>.</p>

        <p>I would like to point out that data transmission on the internet (e.g. communication by e-mail) can have security gaps. Complete protection of data against access by third parties is not possible.</p>

        <h5>SSL or TLS encryption</h5>
        <p>For security reasons and to protect the transmission of confidential content, such as enquiries that you send to me as the site operator, this site uses SSL or TLS encryption. You can recognise an encrypted connection by the fact that the address line of the browser changes from "http://" to "https://" and by the lock symbol in your browser line. If SSL or TLS encryption is activated, the data you transmit to me cannot be read by third parties.</p>

        <h4><li>Techniques used on this website</li></h4>
        <h5>Cookies</h5>
        <p>This website only uses technical and functional cookies. Analytical cookies that do not violate your privacy are also used. A cookie is a small text file that is stored on your computer, tablet or smartphone when you first visit this website. The cookies used by this website are necessary for the technical operation of the website and your user experience. They ensure that the website works properly and remember, for example, your preferred settings such as the language you have chosen. They also enable me to optimise my website. You can refuse the use of cookies by setting your internet browser to no longer store cookies. You can also delete all previously stored information via your browser settings.</p>
        
        <h5>Server log files</h5>
        <p>The hoster of the pages automatically collects and stores information in so-called server log files, which your browser automatically transmits to him. These are:</p>

        <ul>
            <li>browser type and browser version</li>
            <li>Operating system used</li>
            <li>referrer URL</li>
            <li>Host name of the accessing computer</li>
            <li>Time of the server request</li>
            <li>IP address</li>
        </ul><br />

        <p>As the website operator I have a legitimate interest in the technically error-free presentation and optimisation of my website - for this purpose, the server log files must be collected.</p>

        <p>This data is not merged with other data sources.</p>
    </ol>
</div>