<div style="text-align:justify">
    <h2><?= e($title) ?></h2>

    <h5>Einleitung</h5>
    <p>Diese Website verarbeitet personenbezogene Daten für genealogische Forschungszwecke gemäß Artikel 6 Absatz 1 Buchstabe f der <a class="text-primary href="https://commission.europa.eu/law/law-topic/data-protection/data-protection-eu_de">Europäischen Datenschutz-Grundverordnung</a> (DSGVO) wie sie in dieser Datenschutzerklärung aufgeführt sind. Ich unterscheide dabei zwischen personenbezogenen Daten, die ich zum Zweck meiner genealogischen Forschung verarbeite und personenbezogenen Daten, die Sie mir selbst zur Verfügung stellen wenn Sie ein kostenloses Benutzerkonto auf dieser Website anlegen.</p>

    <ol>
        <h4><li>Persönliche Daten zum Zweck der Ahnenforschung</li></h4>
        <p>Ich verarbeite personenbezogene Daten aus öffentlichen Quellen (Archive, Zeitungen, Websites usw.), aus eigenen Quellen oder weil Sie oder eine andere Person sie mir zum Zweck meiner Ahnenforschung zur Verfügung gestellt haben. Besucher haben nur begrenzten Zugang zu den Daten von Verstorbenen: Personen, die vor mehr als 10 Jahren gestorben sind, oder Personen, die vor mehr als 120 Jahren geboren wurden. Mitglieder mit einem Benutzerkonto haben darüber hinaus Zugang zu:</p>

        <ul>
            <li>Daten von Verstorbenen</li>
            <li>(limitierte) Daten von lebenden Personen, mit denen sie im ersten oder zweiten Grad verwandt sind (Partner, (Stief-)Kind, Enkel, Eltern, Großeltern, Onkel/Tante)</li>
            <li>eigene Daten</li>
        </ul><br />

        <p>Besondere personenbezogene Daten (siehe unten) sind immer geschützt, auch für registrierte nahe Verwandte. Sie können jederzeit Einsicht in Ihre eigenen, für meine Ahnenforschung gesammelten Daten verlangen, auch wenn Sie kein Benutzerkonto haben. Wenn Sie nicht möchten, dass Ihre Daten von registrierten nahen Angehörigen eingesehen werden können, teilen Sie mir dies bitte über das <a href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">Kontaktformular</a> mit.</p>

        <h5>Besondere und/oder sensible personenbezogene Daten</h5>
        <p>Für meine genealogischen Forschungen verarbeite ich spezielle und/oder sensible personenbezogene Daten aus öffentlichen Quellen (Archive, Zeitungen, Websites usw.), aus meinen eigenen Quellen oder weil Sie oder jemand anderes sie mir zur Verfügung gestellt hat. Nachstehend finden Sie eine Liste der besonderen personenbezogenen Daten, die ich zum Zweck meiner genealogischen Forschung verarbeiten kann:</p>

        <ul>
            <li>rassische oder ethnische Herkunft</li>
            <li>politische Meinungen</li>
            <li>Religion oder Weltanschauung</li>
            <li>Gewerkschaftsmitgliedschaft</li>
            <li>Gesundheit</li>
            <li>Vorstrafenregister</li>
        </ul><br />

        <p>Ich gebe diese Daten erst 10 Jahre nach Ihrem Tod frei. Dies gilt auch für Daten, die aus öffentlichen Quellen stammen.</p>

        <h5>Speicherdauer Ihrer persönlichen Daten</h5>
        <p>Ihre personenbezogenen Daten werden nicht länger aufbewahrt, als es für die Erfüllung der Zwecke, für die sie erhoben wurden, unbedingt erforderlich ist. Wenn Sie 3 Jahre lang nicht mehr auf unserer Website aktiv waren, wird Ihre Mitgliedschaft beendet und die mit Ihrem Konto verbundenen personenbezogenen Daten werden gelöscht. Die persönlichen Daten, die auf Ihrer persönlichen Seite zum Zweck meiner genealogischen Forschung verarbeitet werden, werden niemals gelöscht. Ich bin der Meinung, dass diese Daten für meine Ahnenforschung von historischer Bedeutung sind.</p>

        <p>Sie können jedoch von mir verlangen, dass diese Daten nur vom Forscher selbst und nicht von registrierten nahen Angehörigen eingesehen werden dürfen. Ihre persönliche Seite ist daher für Mitglieder dieser Website vollständig geschützt. Ihre Daten sind auch vor Besuchern dieser Website stets geschützt.</p>

        <h5>Weitergabe von personenbezogener Daten an Dritte</h5>
        <p>Die Daten auf dieser Website dürfen nur für persönliche Zwecke verwendet werden.</p>

        <p><strong>Jede andere Verwendung dieser Daten ist ausdrücklich untersagt.</strong></p>

        <p>Ich gebe Ihre Kontodaten niemals an Dritte weiter. Die Bereitstellung von Stammbaumdaten für Dritte (andere Genealogen) ist auf Personen beschränkt, die vor mehr als 10 Jahren gestorben sind. Ich gebe die Daten, die ich über Sie und andere lebende Familienmitglieder gesammelt habe, niemals zum Zweck der Ahnenforschung weiter, es sei denn, Sie geben Ihre ausdrückliche Zustimmung.</p>

        <h4><li>Persönliche Daten zum Zweck eines Benutzerkontos auf dieser Website</li></h4>
        <p>Diese Website verarbeitet Ihre personenbezogenen Daten auf der Grundlage von Art. 6 Abs. 1 lit. f DSGVO, wenn Sie mir diese bei der Einrichtung eines Kontos selbst zur Verfügung stellen. Im Folgenden finden Sie einen Überblick über die personenbezogenen Daten, die ich verarbeite, wenn Sie ein Benutzerkonto anlegen:</p>

        <ul>
            <li>Name</li>
            <li>E-Mail Adresse</li>
            <li>IP-Adresse</li>
            <li>Andere personenbezogene Daten, die Sie aktiv zur Verfügung stellen, z. B. indem Sie Ihre persönlichen Daten auf Ihrer Personenseite vervollständigen oder indem Sie Familienverbindungen herstellen. Dazu gehören auch zusätzliche Informationen, die Sie mir per E-Mail oder auf andere Weise zur Verfügung stellen.</li>
            <li>Daten über Ihre Aktivitäten auf dieser Website</li>
        </ul><br />

         <h5>Verwendung</h5>
        <p>Ich verwende Ihre E-Mail-Adresse gelegentlich, um Sie per E-Mail über wichtige Angelegenheiten im Zusammenhang mit der Website zu informieren oder um Sie gegebenenfalls zu kontaktieren. Wenn Sie Ihr Benutzerkonto löschen, bleiben die genealogischen Daten auf Ihrer Personenseite zum Zweck meiner genealogischen Forschung erhalten.</p>

        <h5>Daten einsehen, korrigieren oder löschen</h5>
        <p>Sie haben das Recht, Ihre persönlichen Daten, die zu Ihrem Benutzerkonto gehören, einzusehen, zu korrigieren oder zu löschen. Sie können dies selbst über die persönlichen Einstellungen Ihres Kontos tun. Sie haben auch das Recht, Ihre eventuelle Zustimmung zur Datenverarbeitung zu widerrufen oder der Verarbeitung Ihrer personenbezogenen Daten zu widersprechen. Sie haben das Recht auf Einsichtnahme und Berichtigung der Daten, die ich zum Zweck meiner Ahnenforschung über Sie gesammelt habe. Sie können auch verlangen, dass ich diese Daten niemals an Dritte weitergebe, solange Sie noch leben.</p>

        <p>Wenn Sie von Ihrem Widerspruchsrecht Gebrauch machen möchten oder sonstige Fragen/Anmerkungen zur Datenverarbeitung haben, nutzen Sie bitte das <a href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">Kontaktformular</a>, um mir eine detaillierte Anfrage zukommen zu lassen.</p>

        <h4><li>Beschwerderecht bei der zuständigen Aufsichtsbehörde</li></h4>
        <p>Im Falle von Verstößen gegen die DSGVO steht den Betroffenen ein Beschwerderecht bei einer Aufsichtsbehörde, insbesondere in dem Mitgliedstaat ihres gewöhnlichen Aufenthalts, ihres Arbeitsplatzes oder des Orts des mutmaßlichen Verstoßes zu. Das Beschwerderecht besteht unbeschadet anderweitiger verwaltungsrechtlicher oder gerichtlicher Rechtsbehelfe.</p>

        <h4><li>Hosting</h4></li>
        <p>Diese Website wird bei einem externen Dienstleister gehostet (Hoster). Die personenbezogenen Daten, die auf dieser Website erfasst werden, werden auf den Servern des Hosters gespeichert. Hierbei kann es sich v. a. um IP-Adressen, Kontaktanfragen, Meta- und Kommunikationsdaten, Vertragsdaten, Kontaktdaten, Namen, Websitezugriffe und sonstige Daten, die über eine Website generiert werden, handeln. Mein Hoster wird Ihre Daten nur insoweit verarbeiten, wie dies zur Erfüllung seiner Leistungspflichten erforderlich ist und meine Weisungen in Bezug auf diese Daten befolgen.</p>

        <p>Der Einsatz des Hosters erfolgt im Interesse einer sicheren, schnellen und effizienten Bereitstellung meines Online-Angebots durch einen professionellen Anbieter (Art. 6 Abs. 1 lit. f DSGVO). Ich setze hierfür folgenden Hoster ein:<p/>

        <p>STRATO AG<br />
        Pascalstraße 10<br />
        10587 Berlin</p>

        <h5>Vertrag über Auftragsverarbeitung</h5>
        <p>Um die datenschutzkonforme Verarbeitung zu gewährleisten, habe ich einen Vertrag über Auftragsverarbeitung mit meinem Hoster geschlossen.</p>

        <h4><li>Wie werden Ihre persönlichen Daten geschützt?</li></h4>
        <p>Ich nehme den Schutz Ihrer Daten ernst und treffe geeignete Maßnahmen, um Missbrauch, Verlust, unbefugten Zugriff, unerwünschte Offenlegung und unbefugte Änderung zu verhindern. Wenn Sie den Eindruck haben, dass Ihre Daten nicht ordnungsgemäß gesichert sind oder es Hinweise auf einen Missbrauch gibt, wenden Sie sich bitte über das <a href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">Kontaktformular</a> an mich.</p>

        <p>Ich weise darauf hin, dass die Datenübertragung im Internet (z. B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.</p>

        <h5>SSL- bzw. TLS-Verschlüsselung</h5>
        <p>Diese Seite nutzt aus Sicherheitsgründen und zum Schutz der Übertragung vertraulicher Inhalte, wie zum Beispiel Anfragen, die Sie an mich als Seitenbetreiber senden, eine SSL- bzw. TLS-Verschlüsselung. Eine verschlüsselte Verbindung erkennen Sie daran, dass die Adresszeile des Browsers von „http://“ auf „https://“ wechselt und an dem Schloss-Symbol in Ihrer Browserzeile. Wenn die SSL- bzw. TLS-Verschlüsselung aktiviert ist, können die Daten, die Sie an mich übermitteln, nicht von Dritten mitgelesen werden.</p>

        <h4><li>Techniken, die auf dieser Website verwendet werden</li></h4>
        <h5>Cookies</h5>
        <p>Diese Website verwendet nur technische und funktionale Cookies. Es werden auch auch analytische Cookies verwendet, die Ihre Privatsphäre nicht verletzen. Ein Cookie ist eine kleine Textdatei, die auf Ihrem Computer, Tablet oder Smartphone gespeichert wird, wenn Sie diese Website zum ersten Mal besuchen. Die von dieser Website verwendeten Cookies sind für den technischen Betrieb der Website und Ihre Benutzerfreundlichkeit erforderlich. Sie sorgen dafür, dass die Website ordnungsgemäß funktioniert und merken sich zum Beispiel Ihre bevorzugten Einstellungen wie die von Ihnen gewählte Sprache. Sie ermöglichen es mir auch, meine Website zu optimieren. Sie können die Verwendung von Cookies ablehnen, indem Sie Ihren Internet-Browser so einstellen, dass keine Cookies mehr gespeichert werden. Außerdem können Sie über Ihre Browsereinstellungen alle zuvor gespeicherten Informationen löschen.</p>
        
        <h5>Server-Log-Dateien</h5>
        <p>Der Hoster der Seiten erhebt und speichert automatisch Informationen in so genannten Server-Log-Dateien, die Ihr Browser automatisch an ihm übermittelt. Dies sind:</p>

        <ul>
            <li>Browsertyp und Browserversion</li>
            <li>verwendetes Betriebssystem</li>
            <li>Referrer URL</li>
            <li>Hostname des zugreifenden Rechners</li>
            <li>Uhrzeit der Serveranfrage</li>
            <li>IP-Adresse</li>
        </ul><br />

        <p>Als Websitebetreiber habe ich ein berechtigtes Interesse an der technisch fehlerfreien Darstellung und der Optimierung meiner Website – hierzu müssen die Server-Log-Files erfasst werden.</p>

        <p>Eine Zusammenführung dieser Daten mit anderen Datenquellen wird nicht vorgenommen.</p>
    </ol>
</div>
