<div style="text-align:justify">
    <h2><?= e($title) ?></h2>

    <h5>Inleiding</h5>
    <p>Deze website verwerkt persoonsgegevens voor genealogisch onderzoek in overeenstemming met artikel 6 eerste alinea onderdeel f) van de <a class="text-primar" href="https://commission.europa.eu/law/law-topic/data-protection/data-protection-eu_nl">Europese Algemene Verordening Gegevensbescherming</a> (AVG) zoals uiteengezet in deze privacyverklaring. Ik maak onderscheid tussen persoonsgegevens die ik verwerk ten behoeve van mijn genealogisch onderzoek en persoonsgegevens die u zelf aan mij verstrekt wanneer u een gratis gebruikersaccount aanmaakt op deze website.</p>

    <ol>
        <h4><li>Persoonsgegevens ten behoeve van genealogisch onderzoek</li></h4>
        <p>Ik verwerk persoonsgegevens uit openbare bronnen (archieven, kranten, websites, etc.), uit eigen bronnen of omdat u of iemand anders deze aan mij heeft verstrekt ten behoeve van mijn genealogisch onderzoek. Bezoekers hebben beperkte toegang tot de gegevens van overleden personen: Personen die meer dan 10 jaar geleden zijn overleden, of personen die meer dan 120 jaar geleden zijn geboren. Leden met een gebruikersaccount hebben ook toegang tot:</p>

        <ul>
            <li>gegevens van overledenen</li>
            <li>(beperkte) gegevens van levende personen aan wie zij in de eerste of tweede graad (partner, (stief)kind, kleinkind, ouder, grootouder, oom/tante) verwant zijn</li>
            <li>eigen gegevens</li>
        </ul><br />

        <p>Bijzondere persoonsgegevens (zie hieronder) worden altijd afgeschermd, ook voor geregistreerde naaste familieleden. U kunt altijd een verzoek indienen om uw eigen gegevens te mogen inzien die ik voor mijn genealogisch onderzoek hebben verzameld, ook als u geen gebruikersaccount heeft. Indien u niet wilt dat uw gegevens kunnen worden ingezien door geregistreerde naaste familieleden, dan kunt u mij dit laten weten via het <a class="text-primar" href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">contactformulier</a>.</p>

        <h5>Bijzondere en/of gevoelige persoonsgegevens</h5>
        <p>Voor mijn genealogisch onderzoek verwerk ik bijzondere en/of gevoelige persoonsgegevens uit openbare bronnen (archieven, kranten, websites, etc), uit eigen bron of doordat u of iemand anders deze aan mij heeft verstrekt. Hieronder vindt u een overzicht van de bijzondere persoonsgegevens die ik mogelijk ten behoeve van mijn genealogisch onderzoek verwerk:</p>

        <ul>
            <li>ras of etnische afkomst</li>
            <li>politieke opvattingen</li>
            <li>godsdienst of levensovertuiging</li>
            <li>lidmaatschap van een vakbond</li>
            <li>gezondheid</li>
            <li>strafrechtelijk verleden</li>
        </ul><br />

        <p>Ik geef deze gegevens niet eerder dan 10 jaar na uw overlijden vrij. Dit is ook van toepassing op gegevens die afkomstig zijn uit openbare bronnen.</p>

        <h5>Bewaartermijn van uw persoonsgegevens</h5>
        <p>Uw persoonsgegevens worden niet langer bewaard dan strikt noodzakelijk is om de doelen te realiseren waarvoor ze zijn verzameld. Als u 3 jaar niet actief bent geweest op onze website, wordt uw lidmaatschap beëindigd en worden de persoonsgegevens die aan uw account zijn gekoppeld verwijderd. De persoonsgegevens die op uw persoonlijke pagina worden verwerkt ten behoeve van mijn genealogisch onderzoek zullen nooit worden verwijderd. Ik ben van mening dat deze gegevens van historisch belang zijn voor mijn genealogisch onderzoek.</p>

        <p>U kunt echter van mij verlangen dat deze gegevens alleen door de onderzoeker zelf en niet door geregistreerde naasten mogen worden ingezien. Uw persoonlijke pagina is dus volledig afgeschermd voor leden van deze website. Uw gegevens zijn ook te allen tijde beschermd tegen bezoekers van deze website.</p>

        <h5>Delen van persoonsgegevens met derden</h5>
        <p>Gegevens op deze website mogen alleen worden gebruikt voor persoonlijke doeleinden</p>

        <p><strong>Ander gebruik van deze gegevens is uitdrukkelijk niet toegestaan.</strong></p>

        <p>Ik verstrek uw accountgegevens nooit aan derden. Het ter beschikking stellen van stamboomgegevens aan derden (andere genealogen) is beperkt tot personen die meer dan 10 jaar geleden zijn overleden. Gegevens die ik ten behoeve van miin genealogisch onderzoek over u en andere nog levende familieleden verzameld heb deel ik nooit met derden, tenzij u daar zelf uitdrukkelijk toestemming voor geeft</p>

        <h4><li>Persoonsgegevens ten behoeve van een gebruikersaccount op deze website</li></h4>
        <p>Deze website verwerkt uw persoonsgegevens wanneer u deze zelf aan mij verstrekt bij het aanmaken van een account. Hieronder vindt u een overzicht van de persoonsgegevens die ik verwerk wanneer u een gebruikersaccount aanmaakt:</p>

        <ul>
            <li>Naam</li>
            <li>E-mailadres</li>
            <li>IP-adres</li>
            <li>Overige persoonsgegevens die u actief verstrekt bijvoorbeeld door uw persoonsgegevens op uw persoonspagina aan te vullen of door het leggen van familiebanden. Hieronder valt ook extra informatie die u mij via e-mail of op andere wijze verstrekt.</li>
            <li>Gegevens over uw activiteiten op deze website</li>
        </ul><br />

         <h5>Gebruik van uw gegevens</h5>
        <p>Ik gebruik uw e-mailadres incidenteel om u te mailen over belangrijke zaken met betrekking tot de website of om contact met u op te nemen indien dat noodzakelijk is. Wanneer u uw gebruikersaccount verwijderd blijven de genealogische gegevens op uw persoonspagina behouden ten behoeve van mijn genealogisch onderzoek.</p>

        <h5>Gegevens inzien, aanpassen of verwijderen</h5>
        <p>U heeft het recht om uw persoonsgegevens behorende bij uw gebruikersaccount in te zien, te corrigeren of te verwijderen. Dit kunt u zelf doen via de persoonlijke instellingen van uw account. Daarnaast heeft u het recht om uw eventuele toestemming voor de gegevensverwerking in te trekken of bezwaar te maken tegen de verwerking van uw persoonsgegevens. U heeft het recht om de gegevens die ik ten behoeve van mijn genealogisch onderzoek over u heb verzameld in te zien en te corrigeren. Ook kunt u van mij verlangen dat deze gegevens nooit aan derden wordt verstrekt zolang u in leven bent.</p>

        <p>If you wish to exercise your right to object or have other questions/comments about data processing, please use the <a class="text-primar" href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">contact form</a> to send me an itemised request.</p>

        <h4><li>Recht van beroep bij de bevoegde toezichthoudende autoriteit</li></h4>
        <p>In geval van inbreuken op de AVG hebben betrokkenen het recht in beroep te gaan bij een toezichthoudende autoriteit, met name in de lidstaat van hun gewone verblijfplaats, hun werkplek of de plaats van de vermeende inbreuk. Het recht van beroep laat andere administratieve of gerechtelijke beroepsmogelijkheden onverlet.</p>

        <h4><li>Hosting</h4></li>
        <p>Deze website wordt gehost door een externe dienstverlener (hoster). De op deze website verzamelde persoonsgegevens worden opgeslagen op de servers van de hoster. Het kan gaan om IP-adressen, contactverzoeken, meta- en communicatiegegevens, contractgegevens, contactgegevens, namen, website-toegangen en andere gegevens die via een website worden gegenereerd. Mijn hoster verwerkt uw gegevens alleen voor zover dat nodig is om aan zijn prestatieverplichtingen te voldoen en volgt mijn instructies met betrekking tot die gegevens op.</p>

        <p>De hoster wordt gebruikt in het belang van een veilige, snelle en efficiënte levering van mijn online aanbod door een professionele aanbieder. Ik gebruik hiervoor de volgende hoster:<p/>

        <p>STRATO AG<br />
        Pascalstraße 10<br />
        10587 Berlijn</p>

        <h5>Orderverwerkingsovereenkomst</h5>
        <p>Met het oog op een gegevensbeschermingsconforme verwerking heb ik met mijn hoster een orderverwerkingsovereenkomst gesloten.</p>

        <h4><li>Hoe worden uw persoonsgegevens beveiligd?</li></h4>
        <p>Ik neem de bescherming van uw gegevens serieus en neem passende maatregelen om misbruik, verlies, onbevoegde toegang, ongewenste openbaarmaking en ongeoorloofde wijziging tegen te gaan. Als u de indruk heeft dat uw gegevens niet goed beveiligd zijn of er aanwijzingen zijn van misbruik, neem dan contact op via het <a class="text-primar" href="https://www.ravenzwaaij.info/tree/ravenzwaaij/message-compose?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Fmodule%2F_privacy_footer_%2FPage%2Fravenzwaaij">contactformulier</a>.</p>

        <p>Ik wijs erop dat gegevensoverdracht via internet (bijv. communicatie per e-mail) hiaten in de beveiliging kan vertonen. Volledige bescherming van gegevens tegen toegang door derden is niet mogelijk.</p>

        <h5>SSL- of TLS-codering</h5>
        <p>Om veiligheidsredenen en ter bescherming van de overdracht van vertrouwelijke inhoud, zoals aanvragen die u aan mij als beheerder van de site stuurt, maakt deze site gebruik van SSL- of TLS-codering. U kunt een versleutelde verbinding herkennen aan het feit dat de adresregel van de browser verandert van "http://" in "https://" en aan het slotsymbool in uw browserregel. Als de SSL- of TLS-codering is geactiveerd, kunnen de gegevens die u aan mij doorgeeft niet door derden worden gelezen.</p>

        <h4><li>Op deze website gebruikte technieken</li></h4>
        <h5>Cookies</h5>
        <p>Deze website gebruikt alleen technische en functionele cookies. Er worden ook analytische cookies gebruikt die uw privacy niet schenden. Een cookie is een klein tekstbestand dat bij het eerste bezoek aan deze website op uw computer, tablet of smartphone wordt opgeslagen. De cookies die deze website gebruikt zijn noodzakelijk voor de technische werking van de website en uw gebruikerservaring. Ze zorgen ervoor dat de website goed werkt en onthouden bijvoorbeeld uw voorkeursinstellingen zoals de door u gekozen taal. Ze stellen mij ook in staat mijn website te optimaliseren. U kunt het gebruik van cookies weigeren door uw internetbrowser zo in te stellen dat deze geen cookies meer opslaat. U kunt ook alle eerder opgeslagen informatie verwijderen via de instellingen van uw browser.</p>
        
        <h5>Serverlogbestanden</h5>
        <p>De hoster van de pagina's verzamelt en bewaart automatisch informatie in zogenaamde serverlogbestanden, die uw browser automatisch aan hem doorgeeft. Dit zijn:</p>

        <ul>
            <li>browsertype en browserversie</li>
            <li>het gebruikte besturingssysteem</li>
            <li>Referrer URL</li>
            <li>Hostnaam van de bezoekende computer</li>
            <li>Tijdstip van de serveraanvraag</li>
            <li>IP-adres</li>
        </ul><br />

        <p>Als website-exploitant heb ik een gerechtvaardigd belang bij de technisch foutloze presentatie en optimalisatie van mijn website - hiervoor moeten de serverlogbestanden worden verzameld.</p>

        <p>Deze gegevens worden niet samengevoegd met andere gegevensbronnen.</p>
    </ol>
</div>